github:
  prebuilds:
    master: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: false
    addLabel: false
tasks:
  - name: setup
    init: |
      pushd ~
      wget -qO- https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
      ./bin/micromamba shell init -s bash -p ~/micromamba
      source ~/.bashrc
      popd
      micromamba activate 
      micromamba install -n base -y -f .binder/environment.yml
      gp sync-done setup
    command: |
      micromamba activate
      doit serve
  - name: watch
    command: |
      gp sync-await setup
      micromamba activate
      doit watch
ports:
  - port: 5000
  - port: 8000
  - port: 8888
