[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.1,<4"]

[tool.flit.metadata]
dist-name = "jupyterlite"
module = "jupyterlite"
author = "JupyterLite Contributors"
home-page = "https://github.com/jtpio/jupyterlite"
requires-python = ">=3.7"
requires = [
    "entrypoints",
    "jupyter_core >=4.7",
    "tornado >=6.1",
]

[tool.flit.scripts]
jupyter-lite = "jupyterlite.app:main"

[tool.flit.metadata.requires-extra]
test = [
    "pytest",
    "pytest-cov",
]
watch = [
    "watchgod",
]
nbconvert = [
    "nbconvert >=6",
]

[tool.flit.entrypoints."jupyterlite.addon.v0"]
contents = "jupyterlite.addons.contents:ContentsAddon"
federated_extensions = "jupyterlite.addons.federated_extensions:FederatedExtensionAddon"
hash = "jupyterlite.addons.hash:HashAddon"
settings = "jupyterlite.addons.settings:SettingsAddon"
static = "jupyterlite.addons.static:StaticAddon"
