name: jupyterlite-dev
# this is a conda/mamba environment for working on JupyterLite and upstreams

channels:
  - conda-forge/label/jupyterlab_alpha
  - conda-forge

dependencies:
  # build stuff
  - black
  - flit >=3.1
  - isort
  - pyflakes
  # demo stuff
  - jupyter-server-proxy
  - jupyterlab >=3.1.0a11,<4
  - retrolab
  # extra docs tools
  - sphinx-autobuild

  ### DOCS ENV ###
  # runtimes
  - nodejs >=14,<15
  - python >=3.8,<3.9
  # build
  - doit >=0.33,<0.34
  - flit >=3.1
  - pip
  - wheel
  - jsonschema >=3
  - yarn <2
  # docs
  - myst-nb
  - pydata-sphinx-theme
  - pytest-check-links
  - sphinx
  - sphinx-jsonschema
  - sphinxext-rediraffe
  # list of federated extensions for the demo site
  - jupyterlab-drawio
  - jupyterlab-tour >=3.1.0
  - jupyterlab-fasta >=3,<4
  - jupyterlab-geojson >=3,<4
  - theme-darcula
  ### DOCS ENV ###
