name: jupyterlite-dev
# this is a conda/mamba environment for working on JupyterLite and upstreams

channels:
  - conda-forge

dependencies:
  # demo stuff
  - jupyter-server-proxy
  - jupyterlab >=3,<4
  - jupyterlab-classic
  - git
  # extra docs tools
  - sphinx-autobuild

  ### DOCS ENV ###
  # runtimes
  - nodejs >=14,<15
  - python >=3.8,<3.9
  # build
  - doit >=0.33,<0.34
  - flit >=3.1
  - pip
  - wheel
  - yarn <2
  # docs
  - myst-nb
  - pydata-sphinx-theme
  - pytest-check-links
  - sphinx
  ### DOCS ENV ###
