name: jupyterlite-docs

channels:
  - conda-forge
  - nodefaults

dependencies:
  # runtimes
  - nodejs >=14,<15
  - python >=3.8,<3.9
  # build
  - doit >=0.33,<0.34
  - flit >=3.1
  - pip
  - wheel
  - yarn <2
  # docs
  - myst-nb
  - pydata-sphinx-theme
  - sphinx
