name: jupyterlite-docs
# this is a conda/mamba environment for building the JupyterLite documentation

channels:
  - conda-forge
  - nodefaults

dependencies:
  ### DOCS ENV ###
  # runtimes
  - nodejs >=14,<15
  - python >=3.8,<3.9
  # build
  - doit >=0.33,<0.34
  - flit >=3.1
  - pip
  - wheel
  - jsonschema >=3
  - yarn <2
  # cli
  - wheel
  # docs
  - myst-nb
  - pydata-sphinx-theme
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx-jsonschema
  - sphinxext-rediraffe
  # check
  - pytest-check-links
  # test
  - ansi2html
  - pytest-console-scripts
  - pytest-cov
  - pytest-html
  - pytest-xdist
  # list of federated extensions for the demo site
  - ipywidgets
  - bqplot
  - ipycytoscape
  - ipyleaflet
  - ipympl
  - ipycanvas
  - jupyterlab-drawio
  - jupyterlab-tour >=3.1.0
  - jupyterlab-fasta >=3,<4
  - jupyterlab-geojson >=3,<4
  - jupyterlab-kernelspy
  - jupyterlab_miami_nights
  - networkx
  - pandas
  - plotly >=5,<6
  - theme-darcula
  ### DOCS ENV ###

  # this is a UNIX-only dependency, so we don't hoist it to the more-portable binder environment
  - diffoscope
