name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: '*'

env:
  CACHE_EPOCH: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: 'node_modules/'
          key: |
            ${{ env.CACHE_EPOCH }}-${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
      - name: Cache yarn packages
        uses: actions/cache@v2
        id: cache-yarn-packages
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        with:
          path: '.yarn-packages'
          key: |
            ${{ env.CACHE_EPOCH }}-yarn-packages-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ env.CACHE_EPOCH }}-yarn-packages-
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install Python dependencies
        run: |
          python -m pip install build
      - name: Install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          yarn --frozen-lockfile
      - name: Build
        run: |
          yarn build
      - name: Lint
        run: |
          yarn lint
      - name: Test
        run: |
          yarn build:test
          yarn test
